# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b45acdefba081e3dec3fc5a1976bad91b922824f997974b7ac2d0a244ec23b58f635a954f7bc7aaa8e674971002b9050afde8b57a57aa6d4b811eacaf5eb9e47

test:
  secret_key_base: 53330b8b698e3a7b8e9bc21f4b861f1f6ed56d2363afc0da186b947f6da467ddc933c0e1e579de57c356e15be1f7cb785b5c98e1f4307113d26c555c5bd1f08f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
